### ISSUE TITLE
Exceptions when using newer version of lodash

### ISSUE THREAD

**Issue by dlebech** [tarunc/intercom.io#12]
We recently upgraded the `lodash` package to 3.X and now we are seeing exceptions when using the `intercom.io` module, originating from:
https://github.com/tarunc/intercom.io/blob/c18c96c39ffc99a358f02c5714ce5d2c75e5cf9e/lib/intercom.io.js#L6

**Comment by tarunc** [comment]
Thanks for reporting this error. I do appreciate it!

I fixed it in release `v1.0.7`. Please try updating `intercom.io` to `v1.0.7`.

**Comment by dlebech** [comment]
I updated the package and it seems to have solved the problem.

Thank you so much for the quick response!
