### ISSUE TITLE
Methods for retrieving all pages of a resource?

### ISSUE THREAD

**Issue by rolodato** [tarunc/intercom.io#13]
I'm writing custom scripts now to retrieve all the pages of a resource, but can make it pretty and submit a PR to have a `pagedRequest` method or similar. Let me know if you'd like to have this included :)

**Comment by tarunc** [comment]
Yup, sure. We could use that!

And if you don't want to take the time to clean it up, just create a PR/Gist anyways and I can incorporate it into the library at a later date.

**Comment by rolodato** [comment]
Sounds good :+1:

**Comment by rolodato** [comment]
Any chance of releasing this to npm?
