### ISSUE TITLE
Missing tagUsers() method

### ISSUE THREAD

**Issue by nestorvc** [tarunc/intercom.io#14]
There is no tagUsers() method, needed to tag users or companies using intercom as read here: https://doc.intercom.io/api/?php#tag-or-untag-users--companies

**Comment by tarunc** [comment]
There is a [`intercom.createTag`](http://tarunc.github.io/intercom.io/#line-271) method that does this.

Here is an example using it:
```javascript
intercom.createTag({
  "name": "Independent",
  "users": [
  	{"id": "42ea2f1b93891f6a99000427"},
    {"user_id": "22"},
    {"email": "a@b.com"}
  ]
}, cb);
```

That was copied from the intercom documentation, and updated for this this library. I haven't tested it so let me know if that works!

**Comment by nestorvc** [comment]
You are right. It worked out, thanks. However it is confusing as in
Intercom's docs the method is separated on a single function and has a
different name.
