### ISSUE TITLE
Structure for noteObj is ambiguous

### ISSUE THREAD

**Issue by nestorvc** [tarunc/intercom.io#15]
Where can I find what noteObj should be made of. I tried the docs here: http://tarunc.github.io/intercom.io/#notes but is ambiguous. I am using the official Intercom docs here: https://doc.intercom.io/api/?bash#create-a-note but I got the following error: 
`{ [IntercomError: {"type":"error.list","request_id":"ec9d6871-75cd-4a5e-a558-b14b0ab956a4","errors":[{"code":"not_found","message":"User Not Found"}]}]` 

What is the structure for "noteObj"?

**Comment by tarunc** [comment]
`nodeObj` should be what the request body is in intercom.io's API documentation.
In the example, they have:
```javascript
{
  "admin_id" : "21",
  "body": "Text for my note",
  "user": {
    "id" : "5310d8e8598c9a0b24000005"
  }
}
```

For the error you included above, it looks like the User you are trying to create is not found. Are you sure the User you are trying to create a note on exists in intercom.io?

**Comment by nestorvc** [comment]
Thank you very much. The request body solved it.
