### ISSUE TITLE
Publish new npm module version?

### ISSUE THREAD

**Issue by rolodato** [tarunc/intercom.io#17]
I'd love to use the `getPages` method in the released module, any chance of that happening? Thanks!

**Comment by tarunc** [comment]
Sorry, about the delay. Just released it to npm, [here](https://www.npmjs.com/package/intercom.io). 

I've been meaning to do it since you commented on the last issue but I've been busy recently.

**Comment by rolodato** [comment]
Perfect, thanks a bunch!
