### ISSUE TITLE
Bulk add users should take array

### ISSUE THREAD

**Issue by JaKXz** [tarunc/intercom.io#23]
In the documentation, it shows:

```js
Intercom.prototype.bulkAddUsers = function(userObj, cb) {
  return this.request('POST', 'users/bulk', userObj, cb);
}
```

But Intercom's docs say that this API can [only take an array of `userObj`s with a maximum size of 50](https://doc.intercom.io/api/#bulk-user-creation).

Is it just safe to pass an array to the userObj parameter? And as a bonus would it be able to automatically slice the array and send the users 50 at a time?

**Comment by tarunc** [comment]
As per [Intercom's docs](https://doc.intercom.io/api/#bulk-user-creation), `userObj` should be:
```js
{
  users: [{
       "user_id": "25",
       "email": "wash@serenity.io"
  }, {
       "user_id":"26",
       "email": "zoe@serenity.io"
  }]
}
```

**Comment by JaKXz** [comment]
Thanks for the clarification (nice reference too :100:)

Perhaps I'll make a PR when I get the slicing working :smile:
