### ISSUE TITLE
406 Error when calling createUser

### ISSUE THREAD

**Issue by thomasgallagher** [tarunc/intercom.io#29]
var options = {
        apiKey: "HIDDEN",
        appId: "HIDDEN"
      };

      var intercom = new Intercom(options);
      intercom.createUser({
        "email": "tom.gallagher@theappengineers.com",
        "name": "Tom Gallagher"
      }, function(err, res) {
        console.log(err);
        console.log(res);
      });

Results in:

XMLHttpRequest cannot load https://api.intercom.io/users. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 406.
main.js:175758 null

Any ideas?
Many thanks, Tom.

**Comment by tarunc** [comment]
This library is to be used with [NodeJS](https://nodejs.org/en/)-- not the browser. It seems like you are using the browser since you mention XMLHttpRequest and CORS.
