### ISSUE TITLE
markConversationAsRead broken

### ISSUE THREAD

**Issue by ebaizel** [tarunc/intercom.io#31]
[Mark Conversation As Read](https://developers.intercom.io/docs/marking-a-conversation-as-read)

The url that `markConversationAsRead` hits is incorrect.  It should `PUT` to `conversation/<convId>` with a `body` of `read:true`.  Right now looks like it's trying to reply to the last conversation.

**Comment by tarunc** [comment]
Hey man, thanks for letting me know-- I pushed them without any tests.

It should be fixed in the most recent version. You should be able to use it like this:
```javascript
intercom.markConversationAsRead({ id: '147', read: true }).then(resolve, reject);
```

Let me know if that solves your issues! Thanks!

**Comment by ebaizel** [comment]
just tested and it works like a charm.  thanks for the fast turnaround.
