### ISSUE TITLE
Unpublished NPM version

### ISSUE THREAD

**Issue by paton** [tarunc/intercom.io#32]
Quick heads up, it looks like v1.2.0 was unpublished from NPM.

This caused our production app to crash when it attempted (and failed) run `npm install`.

**Comment by tarunc** [comment]
Yup, it was due to a broken release-- see #31

**Comment by paton** [comment]
Generally better to never unpublish (bugs are better than a crashing app).

`npm deprecate` is probably the best bet if you want to notify people who depend on your package

https://docs.npmjs.com/cli/deprecate

**Comment by tarunc** [comment]
Thanks for letting me know. Will be more careful in the future.

**Comment by paton** [comment]
Ps - thanks for your work on this module :)
