### ISSUE TITLE
Company update

### ISSUE THREAD

**Issue by gplancke** [tarunc/intercom.io#9]
Hi there, thanks for your module.

However, impossible to update a company as you use a 'PUT' when the official intercom documentation specify a 'POST' for both creation and update.

Just so you know.

++

**Comment by SethHamilton** [comment]
Yes, this is a bug, needs to be "post" not "put" on update company. Good news, just call createCompany (which seems to be a post) as it calls exactly the same function on in intercom.io

**Comment by tarunc** [comment]
Thanks for the info! Sorry, I didn't get to this for this long. Just changed it. Should work now if you upgrade intercom.io to '1.0.6' but feel free to reopen if it doesn't.
